stages:
  - trigger

trigger_a:
  stage: trigger
  trigger:
    include: ci/services/service-a.yml
    strategy: depend
  rules:
    - changes: [service-a/**/*]

trigger_b:
  stage: trigger
  trigger:
    include: ci/services/service-b.yml
    strategy: depend
  rules:
    - changes: [service-b/**/*]

trigger_c:
  stage: trigger
  trigger:
    include: ci/services/service-c.yml
    strategy: depend
  rules:
    - changes: [service-c/**/*]

trigger_d:
  stage: trigger
  trigger:
    include: ci/services/service-d.yml
    strategy: depend
  rules:
    - changes: [service-d/**/*]
