include:
  - local: ci/templates/base.yml

stages:
  - scan
  - build
  - push
  - update_tf

variables:
  SERVICE_DIR: service-a
  SERVICE_NAME: ingestion_chunker_embedded_run
  IMAGE_URI: $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/service-a/ingestion_chunker_embedded_run

scan_service:
  extends: .default_job
  stage: scan
  script:
    - cd $SERVICE_DIR
    - docker build -t scan-image .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image scan-image
  when: manual

build_service:
  extends: .default_job
  stage: build
  script:
    - cd $SERVICE_DIR
    - docker build -t $IMAGE_URI:$NEW_VERSION .
  when: manual

push_service:
  extends: .default_job
  stage: push
  needs: ["build_service"]
  script:
    - docker push $IMAGE_URI:$NEW_VERSION
    - docker tag $IMAGE_URI:$NEW_VERSION $IMAGE_URI:latest
    - docker push $IMAGE_URI:latest
  when: manual

update_tf:
  stage: update_tf
  image: alpine:latest
  needs: ["push_service"]
  script:
    - apk add --no-cache git curl
    - git clone https://oauth2:$BOT_TOKEN@gitlab.com/$TF_REPO_URL tfrepo
    - cd tfrepo

    - BRANCH=update-$SERVICE_NAME-$NEW_VERSION
    - git checkout -b $BRANCH

    - sed -i "s|container_image *=.*|container_image = \"$IMAGE_URI:$NEW_VERSION\"|" envs/dev/service-a.tfvars

    - git config user.email "ci-bot@company.com"
    - git config user.name "CI Bot"

    - git add .
    - git commit -m "Deploy $SERVICE_NAME $NEW_VERSION"
    - git push origin $BRANCH

    - |
      curl --request POST \
      --header "PRIVATE-TOKEN: $BOT_TOKEN" \
      --data "source_branch=$BRANCH&target_branch=$TF_TARGET_BRANCH&title=Deploy $SERVICE_NAME $NEW_VERSION" \
      https://gitlab.com/api/v4/projects/$TF_PROJECT_ID/merge_requests

  when: manual
